### ISSUE TITLE
The results of the test demo do not quite match the effect presented in the paper

### ISSUE THREAD

**Issue by yyzhuang294** [JoshuaChou2018/SkinGPT-4#7]
![1](https://github.com/user-attachments/assets/13f2b79b-183e-4baa-b0aa-a313ed67e619)
As you can see, the test results of the test image I posted are different from the diagnostic results in the paper, so the open-source demo code is the same as the model set in the paper

**Comment by JoshuaChou2018** [comment]
Hey, thanks for reaching out. As stated in the readme of our repository:

Please note:
- The released trained model above cannot be used for skin disease diagnosis, they can only be used for testing code.
- The latest model trained with both public skin disease datasets and the proprietary skin disease dataset based on falcon-40b-instruct (deprecated) and llama-2-13b-chat-hf (code published only) are not publicly available currently due to privacy issues.

The trained model is under commercialization, please refer to https://dermassure.ai and stay tuned.
